Dataset validity
umr-dbs/wave pull request #96
Opened 2021-02-09 23:20 UTC by rgottsc

Copy dataset validity to layer validity on load & 
Calculate min/max over dataset validity and layer validities in view

2021-02-09 23:21 UTC, rgottsc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dataset listing: Calculate min/max over dataset validity and layer validities in view](https://trello.com/c/vH4g7VNL/14-dataset-listing-calculate-min-max-over-dataset-validity-and-layer-validities-in-view)

2021-02-09 23:21 UTC, rgottsc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dataset: Copy dataset validity to layer validity on load](https://trello.com/c/3eAB6693/13-dataset-copy-dataset-validity-to-layer-validity-on-load)

2021-02-10 10:44 UTC, ChristianBeilschmidt requested changes

2021-02-10 10:44 UTC, ChristianBeilschmidt commented on projects/wave-core/src/lib/users/user.service.ts
> +                                        globalDatasetMaxVal = this.compareStartTime(channelElement.time_end, globalDatasetMaxVal);
```suggestion
                                        globalDatasetMaxVal = this.compareEndTime(channelElement.time_end, globalDatasetMaxVal);
```

2021-02-10 10:44 UTC, ChristianBeilschmidt commented on projects/wave-core/src/lib/users/user.service.ts
> +import {element} from 'protractor';
```suggestion
```

2021-02-17 08:49 UTC, ChristianBeilschmidt approved these changes

2021-02-17 08:49 UTC, merged